name: tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10","3.9", "3.8","3.7"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install maturin
          maturin develop --extras=dev
      - name: Validate types with mypy
        run: |
          source .venv/bin/activate
          pip install mypy
          mypy fast_stats/
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          python -m pytest